vega/voyager

bower.json, src/components/encodingvariations/encodingvariations.html
**Please merge https://github.com/uwdata/vega-lite-ui/pull/13 and publish `vega-lite-ui` first** 
fixes #135
=> Fixing #135  -- prioritize rendering vlplot in modal

bower.json, src/app/fields/fields.js
fixes https://github.com/uwdata/voyager/issues/156
**Please merge #155 first**
=> fix fieldInfo check with type N

src/components/encodingvariations/encodingvariations.html, src/components/vislist/vislist.html
fixes https://github.com/uwdata/vega-lite-ui/issues/22
**Please merge https://github.com/uwdata/vega-lite-ui/pull/23 first**
=> add $index as priority for rendering vislist

src/app/fields/fields.js, src/components/fieldlist/fieldlist.spec.js
https://github.com/uwdata/vega-lite-ui/issues/41
=> migrate vl.field.order to Dataset.fieldOrderBy 

src/components/encodingvariations/encodingvariations.html, src/components/encodingvariations/encodingvariations.scss, src/components/vislist/vislist.html, src/components/vislist/vislist.js
- fixes #170  add infinite-scroll to the vislist  (It turns out that it’s actually quite easy.)
- fixes #169 (Scroll Bar Broken in the modal)
=> add infinite-scroll to the vislist, fixes Scroll Bar Broken in the modal

.travis.yml, src/app/main/main.controller.js, src/app/main/main.html
Like https://github.com/uwdata/polestar/pull/312
=> Embed voyager app

src/app/fields/fields.js, src/app/main/main.controller.js, src/index.html
Companion PR to https://github.com/vega/vega-lite-ui/pull/83 . Google analytics is now incorporated in vlui - so can be removed from voyager.
Also adds a few more events for data loading
=> Add GA Logging to vlui

src/app/main/main.controller.js, src/app/main/main.html
This PR accompanies vega/vega-lite-ui#89
=> Utilize new vl-modal directive for bookmarks modal

src/app/main/main.html
This implements the changes from vega/vega-lite-ui#96 in Voyager
=> Move dataset loading from a Drop to a <modal> directive

src/app/index.scss
part of https://github.com/vega/vega-lite-ui/pull/119
=> remove scss and move it back to vlui

src/app/index.scss, src/app/main/main.html
=> Finalize sidebar header styles

src/app/index.scss, src/app/main/main.html, src/components/encodingvariations/encodingvariations.html, src/components/encodingvariations/encodingvariations.scss, src/components/vislist/vislist.html
Fixes https://github.com/vega/voyager/issues/215
=> Modal and various style fix

bower.json, src/components/encodingvariations/encodingvariations.html, src/components/encodingvariations/encodingvariations.scss
- Add padding and background
- make the `padding-right` to have enough space for scroll bar
Note: the fix for scaling will come in another PR.
=> Fixing encoding variation styles

src/app/visrec/visrec.service.js
Compass API update -- reflecting https://github.com/vega/compass/pull/125  
(This should be merged after a new Compass release)
=> Compass API update

package.json, webpack.config.js, yarn.lock
See: https://webpack.js.org/guides/hmr-react/ for more info
=> Webpack-dev-server

src/actions/shelf.ts, src/components/data-pane/field-list.tsx, src/components/data-pane/index.tsx, src/components/field/field.scss, src/components/field/index.tsx, src/models/shelf/encoding.test.ts, src/models/shelf/encoding.ts, src/models/shelf/index.test.ts, src/models/shelf/index.ts, src/models/shelf/spec.test.ts, src/models/shelf/spec.ts, src/reducers/index.ts, src/reducers/shelf/index.ts, src/reducers/shelf/spec.test.ts, src/reducers/shelf/spec.ts
(Akin to Tableau's Add To Sheet)
=> Add auto add field button

src/models/plot.ts, src/models/shelf/spec.ts
=> Make initially adding count work correctly. 

src/components/app.tsx, src/index.tsx, src/voyager.tsx, yarn.lock
Allow data to be set via prop. Note that this PR is going into the embed wrapper branch.
=> 313 set data store prop

package.json, src/actions/shelf.ts, src/components/plot/index.tsx, src/components/vega-lite/index.tsx, src/components/view-pane/index.tsx, src/models/plot.ts, src/models/shelf/encoding.ts, src/models/shelf/spec.ts, src/reducers/shelf/spec.ts, yarn.lock
I believe I chose the right types in vega-lite for the conversion. 
Right now there is the issue of double imports of vega-util types - but wanted to get this PR started to ensure the changes to types were correct.
=> update to compassql 0.12.0 and vega-lite 2.0.0-beta.3

src/actions/dataset.ts, src/components/app.tsx, src/index.tsx
Clear the shelf and history when changing datasets. Closes #277
[Note this is based off of #346, so that should be merged first]
ping @kanitw 
I also would recommend that we refact datasetLoad and datasetUrlLoad into one datasetLoad function that can either take a URL or InlineData and do the right thing.
=> 277 change dataset

src/actions/dataset.ts, src/components/app.test.ui.tsx, src/components/app.tsx, src/components/data-pane/dataset-selector.tsx, src/lib-voyager.test.ui.tsx
Refactor datasetUrlLoad and datasetLoad into one action creator. Closes #351 
Ping @kanitw and @vlandham
=> Refactor datasetUrlLoad and datasetLoad into one action creator. Closes #351

README.md
=> Fix link to CHI paper

src/actions/dataset.ts, src/actions/result.ts, src/api/api.test.ts, src/api/api.ts, src/selectors/index.ts
@kanitw with this and the latest voyager-server - both api calls should be functional and executable on the server. 
the only thing left is to determine how to populate `serverurl`in `config`.
=> Pass in config from data store. tweak remote buildSchema

package.json, src/api/api.test.ts, src/api/api.ts, src/models/dataset.ts, src/models/plot.test.ts, src/reducers/dataset.test.ts, src/reducers/shelf/spec.test.ts, src/selectors/index.ts, yarn.lock
For #338 - update Voyager to latest version of compassql so as to support table schema.
=> 338 table schema

config/env.js, package.json, src/constants.ts, src/index.tsx, src/models/config.ts, yarn.lock
=> Add SERVER env variable for setting serverUrl.

README.md, package.json
=> Update readme. Update main path in package.json

src/reducers/shelf/spec.ts
@starry97 
These are straightforward renaming, but I'll assign it for you to review since I think it is worth for you look at the pattern of how we use these methods.
=> Rename methods for mutating immutable arrays

package.json, src/api/api.ts, src/components/view-pane/index.tsx, src/lib-voyager.tsx, src/models/index.ts, src/models/plot.test.ts, src/models/plot.ts, src/reducers/shelf/spec.ts, yarn.lock
Make app state serializable. Add helper methods to convert from internal representation to serializable form. Closes #398
pint @kanitw @vlandham
=> Make app state serializable 

package.json, src/components/plot/index.tsx, typings/index.d.ts, yarn.lock
=> click a button to copy spec

package.json, src/components/plot/index.tsx, src/components/plot/plot.scss, typings/index.d.ts, yarn.lock
=> replaced copy button with nicer icon

src/components/app.test.ui.tsx, src/components/data-pane/field-list.tsx, src/components/data-pane/index.tsx, src/components/data-pane/type-changer.scss, src/components/data-pane/type-changer.tsx, src/lib-voyager.test.ui.tsx
=> added type changer ui

package.json
=> Add build dir to jest exclude paths.

package.json, src/components/data-pane/field-list.tsx, src/components/data-pane/type-changer.tsx, src/components/encoding-pane/encoding-shelf.scss, src/components/encoding-pane/encoding-shelf.tsx, src/components/field/index.tsx, yarn.lock
1. Click outside to close popup. Fixed #285
2. Refactor field wrapper into a separate class
=> click outside to close popup

package.json, src/components/app.test.ui.tsx, src/components/app.tsx, src/lib-voyager.test.ui.tsx, src/lib-voyager.tsx, typings/index.d.ts, yarn.lock
Add api to load a vega-lite spec into voyager. Note that this will clear any previously set data. Closes #377
Ping @kanitw. Finally got this going, tests took longer to debug/make run correctly than I expected.
=> Add api to load a vega-lite spec into voyager.

src/actions/dataset.ts, src/actions/result.ts, src/components/data-pane/field-list.tsx, src/components/view-pane/index.tsx, src/selectors/index.ts
=> rename selectors to select.*

src/lib-voyager.tsx
Closes https://github.com/vega/voyager-electron/issues/12
Ping @kanitw
=> fix initialization of voyager instance in lib-voyager. 

src/actions/result.ts, src/components/encoding-pane/index.tsx, src/reducers/index.ts, src/reducers/result.test.ts, src/reducers/result.ts, src/reducers/shelf/index.ts, src/selectors/index.ts, src/store/index.ts, src/store/listener.ts
I think this is definitely an improvement over a hacky solution inside `encoding-pane.ts`.  
That said, if this causes bad effect for loading program state or loading a spec, we could consider other solution.  
In any case, I'll fork from from this branch to work on related views.
=> Use store listener to cause side effect instead.

src/components/plot/index.tsx, src/components/plot/plot.scss
=> moved copied indicator to be below plot buttons

tsconfig.json
... to avoid a loop where output from `tsc` in `build` are also its input
=> Remove `rootDir` from `tsconfig.json`

src/actions/result.ts, src/api/api.ts, src/models/index.ts, src/models/result.ts, src/queries/index.ts, src/reducers/result.test.ts, src/reducers/result.ts, src/store/listener.ts, tsconfig.json
=> Refactor queries related stuff

src/components/app.test.ui.tsx, src/lib-voyager.test.ui.tsx
=> unskip tests

src/selectors/dataset.ts, src/selectors/index.ts, src/selectors/result.ts, src/selectors/shelf.ts
cc: @starry97  
This will prevent the test file from being too bloating.
=> Split `selectors/index.ts` as it is becoming too big

src/components/plot/plot.scss
=> Make specified view scrollbar appear on hover

package.json, yarn.lock
@kanitw Do you want to bump and release Voyager as well?
=> Use CompassQL v0.19.1 and update lock file

src/components/plot/index.tsx
=> hover over non-overflown plot should not move

src/components/encoding-pane/encoding-shelf.tsx
=> Fix unregistered source error

src/components/header/index.tsx
This fixes the voyager-electron issue https://github.com/vega/voyager-electron/issues/19
=> Clicking on IDL logo opens another page

src/models/index.ts, src/selectors/dataset.test.ts, src/selectors/index.test.ts, src/selectors/result.test.ts, src/selectors/shelf.test.ts
=> Add tests for selectors

src/components/field/index.tsx
=> Fix swapping shelf field bug

src/actions/bookmark.ts, src/actions/index.ts, src/components/app.scss, src/components/data-pane/data-selector.scss, src/components/data-pane/data-selector.tsx, src/components/header/bookmark.scss, src/components/header/bookmark.tsx, src/reducers/bookmark.test.ts, src/reducers/bookmark.ts, src/reducers/index.ts
#474 
- Fix overly large React Modal
- Add action and reducer for clearing bookmarks
- Add export bookmarks functionality
=> Add header with `clear all`, `export`, & scrolling functionality in Bookmark Modal

src/components/encoding-pane/filter-pane.tsx, src/components/encoding-pane/one-of-filter-shelf.tsx, src/components/encoding-pane/range-filter-shelf.tsx
1. Fixed domain in temporal filter without time unit
2. Use React.PureComponent
=> Fixed domain in temporal filter without time unit

src/components/data-pane/field-list.tsx, src/components/encoding-pane/encoding-shelf.tsx, src/components/encoding-pane/filter-pane.tsx, src/components/field/index.tsx, src/components/plot/index.tsx
=> Change filterHide => filterShow; hide Number of Records filter icon

src/components/encoding-pane/filter-pane.tsx, src/components/encoding-pane/placeholder.scss
=> Indicate users cannot drop wildcard or number of records to filter pane

src/components/field/field.scss, src/components/field/index.tsx, src/lib-voyager.test.ui.tsx, src/models/shelf/encoding.ts
=> Make Field support FieldDef function name

src/components/encoding-pane/range-filter-shelf.tsx
It throws a warning before if we type numbers in input in quantitative filter.
=> Convert input string to number

src/components/header/bookmark.tsx, src/components/plot/index.tsx
=> Close the modal if the specify button is clicked

src/components/app.test.ui.tsx, src/components/app.tsx, src/components/data-pane/data-selector.tsx, src/components/data-pane/field-list.tsx, src/components/data-pane/index.tsx, src/components/load-data-pane/index.tsx, src/components/load-data-pane/load-data-pane.scss, src/lib-voyager.test.ui.tsx, src/lib-voyager.tsx, src/models/dataset.ts, src/reducers/dataset.test.ts, src/selectors/dataset.ts, src/selectors/result.test.ts
=> Use empty dataset as default app state

package.json, src/actions/shelf.ts, src/components/app.test.ui.tsx, src/components/app.tsx, src/components/data-pane/field-list.tsx, src/components/encoding-pane/encoding-shelf.tsx, src/components/encoding-pane/filter-pane.tsx, src/components/field/index.tsx, src/components/plot/index.tsx, src/reducers/shelf/spec.test.ts, src/reducers/shelf/spec.ts, yarn.lock
Please review and merge #541 first!
=> Add caretShow flag so that we don't have empty space in <Plot>'s <Field>

package.json, src/actions/result.ts, src/components/app.scss, src/components/view-pane/index.tsx, src/components/view-pane/related-views.scss, src/components/view-pane/related-views.tsx, src/components/view-pane/view-pane.scss, src/models/result.ts, src/queries/alternative-encodings.test.ts, src/queries/alternative-encodings.ts, src/queries/base.ts, src/queries/common.ts, src/queries/field-suggestions.test.ts, src/queries/field-suggestions.ts, src/queries/histograms.test.ts, src/queries/histograms.ts, src/queries/index.ts, src/queries/summaries.test.ts, src/queries/summaries.ts, src/reducers/result.test.ts, src/reducers/result.ts, src/selectors/result.test.ts, src/selectors/result.ts, yarn.lock
=> Related Views

package.json, src/components/data-pane/field-list.tsx, yarn.lock
=> Remove Number of Record from count field

src/components/view-pane/index.tsx, src/queries/index.ts, src/selectors/result.ts, src/selectors/shelf.ts
=> Show "no plot" message for the initial view	

src/components/encoding-pane/range-filter-shelf.scss
=> Prevent filter UI from moving when hovered

src/components/plot/bookmarkbutton.tsx, src/components/plot/index.tsx
=> Add title for plot command buttons

src/components/encoding-pane/one-of-filter-shelf.tsx
=> Fix null string in filter

src/models/dataset.ts, src/models/index.ts
This will require less manual interface editing when we change main `State` interface in the future.
=> Refactor Serializable State to be more robust

src/components/encoding-pane/function-picker.tsx, src/components/field/index.tsx, src/models/shelf/encoding.ts, src/models/shelf/function.test.ts, src/models/shelf/function.ts
=> Logic for supporting wildcard function in the shelf

package.json, yarn.lock
Fix https://github.com/vega/voyager/issues/460
=> Fix test coverage line mapping

src/components/data-pane/field-list.scss, src/components/data-pane/field-list.tsx
=> Make field list scrollable

src/models/index.ts, src/reducers/index.ts, src/selectors/index.ts, src/selectors/shelf.test.ts
=> Move config to persistent state

src/components/encoding-pane/encoding-pane.scss, src/components/encoding-pane/filter-pane.scss, src/components/encoding-pane/filter-pane.tsx, src/components/encoding-pane/index.tsx
=> Make filter pane scrollable

src/components/encoding-pane/encoding-shelf.tsx, src/components/encoding-pane/function-picker.scss, src/components/encoding-pane/function-picker.tsx, src/components/field/index.tsx
=> Add Wildcard Function UI

src/components/view-pane/index.tsx, src/components/view-pane/related-views.tsx, src/reducers/result.ts, src/selectors/result.ts
and main gallery
(Now the main gallery will have some limit.)
=> Add new result limit index selector and use it in related-views

src/models/shelf/index.test.ts
=> Clean up and update commented tests in model/shelf/index.test.ts

config/webpack.config.lib.js, scripts/jest-ui.js
=> Revert "Simplify web pack config lib" to fix font-awesome sass issue

src/components/app.tsx, src/lib-voyager.tsx
Voyager side of https://github.com/vega/voyager-electron/issues/18
=> Show file name in data selector when loading Vega-Lite spec and CSV/JSON data

src/actions/dataset.ts, src/components/data-selector/index.tsx
=> Handle errors for load 

src/components/data-pane/field-list.tsx, src/components/encoding-pane/encoding-shelf.tsx, src/components/encoding-pane/filter-pane.tsx, src/components/encoding-pane/range-filter-shelf.tsx, src/components/field/index.tsx, src/components/plot/index.tsx, src/models/shelf/filter.test.ts, src/models/shelf/filter.ts, src/reducers/shelf/filter.ts
=> Handle errors for filter

src/reducers/dataset.ts
=> Refactor schemaReducer to only take schema and action

src/actions/shelf/filter.ts, src/components/encoding-pane/filter-pane.tsx, src/reducers/shelf/filter.test.ts, src/reducers/shelf/filter.ts, src/reducers/shelf/spec.ts
=> Refactor filterReducer to only take filter and action as input	

src/models/export-logs.ts
=> Do not output inline data since it makes the log file too big

package.json, src/components/app-root/index.tsx, src/components/app.scss, src/components/plot-list/index.tsx, src/components/plot-list/plot-list.scss, src/components/view-pane/index.tsx, src/components/view-pane/related-views.tsx, src/constants.ts, src/models/shelf/spec/index.ts, src/selectors/result.test.ts, src/selectors/result.ts, typings/index.d.ts, yarn.lock
=> Loading spinners

src/reducers/index.ts, src/reducers/shelf/index.test.ts, src/reducers/shelf/index.ts, src/reducers/shelf/spec.test.ts, src/reducers/shelf/spec.ts
=> Refactor reducer to separate special case that requires `schema`

src/actions/result.ts, src/components/encoding-pane/index.tsx, src/components/view-pane/index.tsx, src/models/shelf/filter.ts, src/models/shelf/index.test.ts, src/models/shelf/index.ts, src/models/shelf/spec/index.test.ts, src/models/shelf/spec/index.ts, src/reducers/index.test.ts, src/reducers/index.ts, src/reducers/shelf-preview.test.ts, src/reducers/shelf/filter.ts, src/reducers/shelf/index.test.ts, src/reducers/shelf/index.ts, src/reducers/shelf/spec.test.ts, src/reducers/shelf/spec.ts, src/selectors/result.test.ts, src/selectors/shelf.test.ts, src/selectors/shelf.ts, src/store/listener.ts
Part of https://github.com/vega/voyager/issues/617
=> Move `filters` to be a part of `Shelf`, not `ShelfUnitSpec`	

src/api/api.ts, src/components/app.scss, src/components/bookmark/index.tsx, src/components/plot-list/index.tsx, src/components/plot/index.tsx, src/components/vega-lite/index.tsx, src/models/result/plot.ts, src/store/listener.ts, tsconfig.json, typings/vega.d.ts
This is the start for binding data at runtime (for @starry97  to take over)
Fix #652
=> Data binding

src/models/shelf/spec/encoding.ts, src/models/shelf/spec/index.test.ts
Fix https://github.com/vega/voyager/issues/556
=> Convert ordinal to nominal when loading

src/components/vega-lite/index.tsx
=> Add loading spinner for vega lite plot

src/reducers/index.ts
Fix https://github.com/vega/voyager/issues/681
=> Keep log during reset

src/actions/custom-wildcard-field.ts, src/actions/index.ts, src/models/custom-wildcard-field.ts, src/models/index.ts, src/reducers/custom-wildcard-field.test.ts, src/reducers/custom-wildcard-field.ts, src/reducers/index.test.ts, src/reducers/index.ts, src/selectors/index.ts, src/selectors/shelf.test.ts, yarn.lock
=> Add custom-wildcard-field actions, reducers, and selectors

src/lib-voyager.tsx
cc: @ajainarayanan -- you might find this useful as render will now become simpler.
=> Refactor `render` method in `lib-voyager`

src/components/app-root/index.tsx, src/components/app.scss
Part of #731 
Made data and encoding panes resizable
UPDATED GIF:
=> Add Resizable Panes

src/actions/dataset.ts
Fix #715 
Filenames work again :)
And thanks to @ssharif6 for digging around with me last night.
=> Fix missing filename bug

src/actions/index.ts, src/actions/related-views.ts, src/models/index.ts, src/models/related-views.ts, src/models/relatedViewToggler.ts, src/reducers/index.test.ts, src/reducers/index.ts, src/reducers/related-view.test.ts, src/reducers/related-views.ts, src/selectors/index.ts
Part of #634
Note: UI code not covered in this PR, just state changes, action, reducer.
* Add logic to toggle hiding related-views
* Added flag in State to represent if related-views are hidden/unhidden
* Add tests for related-view reducer
* Add missing default state and add missing reducer to combineReducers
=> Add model, action, selector, reducer

src/actions/index.test.ts, src/actions/index.ts
For other apps using Voyager to tell if an action is a Voyager action
=> Export Voyager ACTION_TYPE_INDEX and add isVoyagerAction() 

src/components/vega-lite/index.tsx
=> Remove 'protected' for life cycle methods in VegaLite module

src/lib-voyager.test.ui.tsx, src/lib-voyager.tsx
#748 
Add getBookmarkedSpecs API and test. This returns the list of bookmarked specs from the bookmark.list property.
=> Add getBookmarkedSpecs API and test

README.md, src/actions/related-views.ts, src/components/data-pane/index.tsx, src/components/encoding-pane/index.tsx, src/components/view-pane/index.tsx, src/components/view-pane/related-views-button.tsx, src/components/view-pane/view-pane.scss, src/models/config.ts, src/models/related-views.ts, src/queries/index.ts, src/reducers/related-view.test.ts, src/reducers/related-views.ts
Refactor `hidden` to `collapsed`, as it is more precise.
Update README to link to VoyagerConfig definition & link to `data` format in VL Docs.
=> Refactor hidden to collapsed for related views & update README

src/components/plot/bookmarkbutton.tsx
Add closing popup by clicking outside the alert & modal.
=> Add close popup behavior for bookmark modal & alert

src/components/plot/bookmarkbutton.scss, src/components/plot/bookmarkbutton.tsx
Fix #773 
Small UI bug fix. Adjust casing and add hover css property for Bookmark & adjust font to sans-serif
=> Adjust casing & add hover css property

src/components/data-pane/field-list.scss, src/components/data-pane/field-list.tsx
=> Add css property when wildcards are disabled
