README.md

Resolves #180 
Adds the simple instruction to first `cd` into the locally cloned repository before attempting to run `npm install` and friends.
Also trims excess end-of-line whitespace in several locations.

Clarify install process for npm, bower dependencies

---

README.md
package.json

- Resolve missing peer dependencies that cause errors with NPM3
- Add npm script aliases for gulp commands
- Auto-install bower packages on `npm install` using a postinstall script

NPM3 compatibility and NPM script aliases for Gulp tasks

---

.travis.yml

Global bower installation and explicit `bower install` should no longer be necessary for the Travis CI process to execute successfully, following #184

Remove unnecessary steps from travis configuration

---

src/app/main/main.html
src/index.html

See vega/vega-lite-ui#73 and vega/polestar#322
This was introduced in dea6557d32c7733d220bd5dfca7bcc62f22b4dc8 while addressing an issue that prevented the bookmarks from closing: the display height issue arose due to the introduction of another layer of nesting that the CSS did not account for.
The same angular hierarchy can be achieved with less DOM nesting, so this commit addresses the overflow by removing unneeded intermediate div nodes.
Note that this did not end up being an issue with vega-lite-ui, so this closes vega/vega-lite-ui#73 as a dupe of an issue that exists separately within polestar and voyager.
Polestar commit to follow.

Fix issue where display area does not take up full height

---

src/components/vislist/vislist.js

This closes #176, where the visualization list would not automatically re-render until you mouseover a pill. The reason this was happening was that the update method is debounced, and debounced methods execute outside of Angular's regular digest cycle. As such, while the Visrec object was updated, the change would not take effect until a mouseover or some other angular event handler fires, triggering a new $digest.
We could solve this problem by manually `scope.$digest`ing, but this is the use-case `$apply` was intended for: wrapping the update method in `$apply` is the most concise solution to the problem.

Re-render the visualization list when dataset changes

---

src/app/index.scss
src/app/main/main.controller.js
src/app/main/main.html

Note that this does work better for many links when there is sufficient room: if we add in the tour link, and debug mode is enabled (otherwise those other two don't display), I don't know any way to avoid that hanging bullet on the first line:
Facebook's solution (from #205) has the same problem, and it wouldn't happen in debug mode, so this may not be an issue at all.
Alternate option for the separator would be the smaller dot `\000b7` instead of the bullet &bull;, which might actually be what FB uses:

Try Implementing inline-block footer links as described in #205

---

src/app/index.scss

The CSS intended to hide a tooltip when it is not open does not work due to a CSS selector precedence issue in the angular-tooltip code. Using `!important` is generally not best-practice, but it does let us temporarily work around the problem described in issue #200 and 720kb/angular-tooltips#95
Once this issue is resolved in the angular-tooltips library this code can be deprecated and removed.

Workaround for tooltip opacity issue (fixes #200)

---

src/components/vislist/vislist.html
src/components/vislist/vislist.scss

Make visual hierarchy clearer with background for section header in the `.vis-list`
Fixes #206
The following screenshots also show darker header background color from https://github.com/vega/vega-lite-ui/pull/123. 
Scrolling down we can see that the header is slightly different from the chart's white background.
Not sure if I should make it darker to make the distinction clearer, but we should make it too dark as the logos are designed for white or almost white background.  Otherwise, we have to switch to solid color logo, at least for the IDL logo.  
@vlandham @domoritz  -- ready for review

Make visual hierarchy clearer with background for section header in the `.vis-list`

---

src/app/main/main.html

`Bookmarks` service in vega-lite-ui no longer has `.length`. We read `Bookmarks.list.length` instead.

Get Bookmarks.list.length

---

package.json
webpack.config.js

In order to get source maps working for SASS, had to switch to the `source-map` devtool, which is [recommended by `extract-text`](https://github.com/webpack-contrib/extract-text-webpack-plugin/tree/58dd5d31735dd801cba43c87700f4d6144203c75#usage).
I also had to stop using the `-d` CLI flag for `webpack`, because it overrides `devtool` and replaced it with `--debug`, which it includes.

Get style source maps working (fixes #281)

---

src/components/app.tsx
src/index.tsx

This is a fix to a regression i am seeing where the dataset selector isn't being shown when no config is passed. I thought this was addressed in #340 but must have missed something. This sets it explicitly in the app. 
I'll try to track down whats happening with the default but this should be good to keep anyway.

fixes a regression introduced in #340. show dataset selector in app

---

src/api/api.ts

For voyager-server, we need to call voyager code to generate recommend output. One way to do that is just to call the `api` function - as we would on the client. 
A problem with every scenario i've found so far is when trying to use class declarations directly from compassql, typescript cannot tell that the class declarations from compassql and the class declarations from compassql -> voyager are the same class.
For example, `fetchCompassQLRecommend` takes a `Schema` instance. This `Schema` comes from compassql, but typescript gives an error as it cannot discover that. 
The option to get around this is presented in this PR. We basically export compassql types somewhere in voyager (here they are in the api - but it could be a separate file). and then we can use these types instead of types …

export types used in api

---

src/components/plot/index.tsx

bug fix
Previous bug: cannot remove specifying spec shelf.

fixed previewing shelf cannot be removed

---

config/webpack.config.dev.js
config/webpack.config.prod.js
config/webpack.lib.config.js
src/components/header/index.tsx
typings/index.d.ts

This is a fix for https://github.com/vega/voyager-electron/issues/10, using the webpack will allow the files to be copied over during the build.
ping @kanitw @starry97

Load header images with web pack loader.

---

config/webpack.config.dev.js
config/webpack.config.prod.js
config/webpack.lib.config.js

Closes https://github.com/vega/voyager-electron/issues/16
Embedding the image as a data:uri should avoid any path issues in embedding contexts.

Use url loader for images (e.g. logo). 

---

src/models/dataset.ts

so we can enforce the type to be not just quantitative
cc: @starry97 @felixcodes -- here is one way to avoid error when TS is not very smart with string literal is a more complex structure.  
(I suspect that newer version of TS would get better at this though.)

Remove `as` from DEFAULT_DATASET and use PrimitiveType.*  instead

---

src/components/plot/bookmarkbutton.scss
src/components/plot/bookmarkbutton.tsx
src/components/plot/index.tsx
src/components/plot/plot.scss

Related to #482. 
It does not change the size of icons, because the FontAwesome icons we use have different sizes. Adding more spaces make them look better.

Add more padding to plot icons; change color to be consistent

---

src/components/data-pane/data-selector.tsx

#478 
- Add `className='voyager'` to the Modal to resize everything back to normal.

Fix size issue in Data Selector modal

---

src/components/plot/index.tsx

- Remove `<span>` surrounding the clipboard icon since it caused the clipboard's hitbox to extend onto the bookmark icon to its left. This would cause the spec to be copied when the right side of the bookmark icon was clicked (shown below).
Before:

Fix `copy-to-clipboard` plot command hitbox

---

src/components/field/index.tsx

When draggable is set to false, the field cannot be dragged.
Fix #525

Fix undraggable field

---

src/components/encoding-pane/encoding-shelf.tsx
src/components/encoding-pane/index.tsx
src/components/field/index.tsx

Previously there was a bug preventing the encoding field being moved to another shelf, now this is fixed.

Fix moving encoding field

---

.travis.yml

This means that we should always make sure to run `npm run test` locally before submitting a PR.

Disable UI test on Travis temporarily

---

src/components/plot/index.tsx
src/components/plot/plot.scss

Make bookmark notes style consistent with the old app.
Fix #518

Fix bookmark notes css

---

src/components/plot-list/index.tsx
src/components/plot/index.tsx
src/components/plot/plot.scss
src/components/view-pane/index.tsx

- Add `onSort` to Plot so that its parent can specify the right action, depending where they are
- For ViewPane, do `SpecFieldPropChange`
- For PlotList, do `ResultModifyFieldProp`

Add basic sort toggle button

---

src/components/encoding-pane/encoding-shelf.scss

Fix style for encoding fields with long names

---

config/webpack.config.prod.js

- Set webpack output `publicPath` to empty string to remove the leading '/' in asset URLs.

Fix output src of HTML and CSS in production Webpack config

---

src/components/data-pane/index.tsx
src/components/encoding-pane/index.tsx
src/components/view-pane/index.tsx
src/models/config.ts
src/queries/index.ts

Add `manualSpecificationOnly` flag to VoyagerConfig

---

src/selectors/result.ts

(since the plots will already have data when we generate the results)

Make `selectData` no longer required in selectMainSpec/selectPlotList

---

config/webpack.config.lib.js
yarn.lock

Fix #668 
Setting `transpileOnly: true` in lib config's `ts-loader` removes the nested build folder created when we run `webpack.config.lib` in our postbuild script. Normally setting `transpileOnly: true` is a bad idea because it leaves us without type checking, but we always `tsc` prior to `webpack.config.lib` in postbuild which takes care of type checking.

Set `transpileOnly: true` in `ts-loader` to remove nested build folder created in postbuild

---

config/webpack.config.prod.js

Fix #660 - Our logos are back!
- Remove redundant `png` from url-loader as we were running them through url-loader twice

Remove png from url-loader to fix corrupting image files

---

src/components/data-selector/index.tsx

Fix #666 
Turns out we don't need `this.closeModal()` to close the modal when we upload a dataset.

Fix setState warning when uploading a dataset

---

config/webpack.config.dev.js
package.json
src/components/app-root/index.tsx
src/lib-voyager.tsx
src/models/config.ts

- Add default embed configuration to `VoyagerConfig`.
- Currently it supports hiding header and footer.
- This configuration basically gives an option to not render the header and footer when embedding voyager in another application.
- By default the header and footer are rendered. So existing setup requires no change.
Created this as part of the discussion that went in this Issue: https://github.com/vega/voyager/issues/673
- Have not modified any docs. Not sure if this is the final implementation or if there is a simpler way to do this.

Add optional config when embedding voyager as library

---

scripts/jest-ui.js

- React warns users when a minified build of react is run in a non-production environment
- Recently we started using UgilifyJS webpack plugin to uglify final library build. However since we used the same webpack config it was minifying development version of react which was causing the issue.(UI test build runs with `NODE_ENV === 'test'` and react expects this to be `production` if minified).
- Avoids uglifying code when running ui test build.
Fixes https://github.com/vega/voyager/issues/702

Avoids uglifying library when running test build #702

---

src/actions/shelf/index.ts
src/components/view-pane/index.tsx
src/components/view-pane/related-views-button.scss
src/components/view-pane/related-views-button.tsx
src/components/view-pane/view-pane.scss

Part of Issue: #634 
Add UI & connect hide/show RelatedViews button component to state
Note: Linter added several diffs via adding spaces around imports and other style features.
Quick gif

Add hide/show toggle component

---

src/lib-voyager.test.ui.tsx
src/lib-voyager.tsx

Add `getSpec` to lib-voyager to export Vega-Lite spec for current specified view.
`getSpec` accepts a boolean value indicating whether or not to attach data payload (inline) in request. 
Fix #746

Add getSpec handler to lib-voyager

---

src/actions/index.ts
src/models/index.ts
src/reducers/index.ts
src/selectors/dataset.ts
src/selectors/index.ts
src/selectors/result.ts
src/selectors/shelf.ts
src/selectors/tab.ts
src/store/index.ts

Make state generic for other apps to extend

---

src/queries/index.ts
src/store/listener.ts

Stop compassQL for querying related views when related-views toggle mode is on.

Stop query compassQL when related-views tab hidden

---

src/components/encoding-pane/encoding-shelf.tsx

Fix #775 
Only allow property-editor pane to be opened when `fieldDef` is defined.

Fix closing customizer bug

---

src/components/data-pane/index.tsx
src/components/encoding-pane/index.tsx
src/models/config.ts

Refactor VoyagerConfig to have property `wildcards` with possible values `enabled|disabled` and property `relatedViews` with possible values `initiallyCollapsed | initiallyShown | disabled`
Case 1: `relatedViews: disabled`, `wildcards: enabled`
Case 2: `relatedViews: initiallyCollapsed`, `wildcards: enabled`
Case 3: `relatedViews: initiallyShown`, `wildcards: disabled`

Add wildcards property to VoyagerConfig

---

src/models/shelf/spec/encoding.ts

Needed for #789 
Add stack property to `ShelfFieldDef` interface so can recreate formData for custom-encoding.

Add stack to ShelfFieldDef

---

src/components/vega-lite/index.tsx
typings/vega.d.ts

Add viewRunAfterCallback in VegaLite props

---

scripts/build.js
src/components/vega-lite/index.tsx
typings/vega.d.ts

Please merge https://github.com/vega/voyager/pull/776 first
This PR fix https://github.com/vega/voyager/issues/739
I add a `copyScss()` function in `scripts/build.js` to copy the style files from `/src` to `/build` folder. This allows external apps to reuse Voyager components with style.

Copy .scss files from src to build folder 

---

src/components/encoding-pane/encoding-shelf.tsx
src/components/encoding-pane/field-customizer.scss
src/components/encoding-pane/field-customizer.tsx
src/components/encoding-pane/property-editor-schema.ts
src/components/encoding-pane/property-editor.tsx
src/models/shelf/spec/encoding.ts

Extension of PR #789  and part of Issue #757
* Add support for Positional & Mark property channels (except text and detail, as `format` prop is not supported in Compass yet).
* Click outside of form will close field-customizer
Schema design & gifs for each mark encoding found here (for mark channels): https://docs.google.com/document/d/1n4pd6q3jMbZ_BYoSLYsMzTV9NOc25ZTJZ8oAGav3zP4/edit?usp=sharing

More Custom Encoding

---

.vscode/settings.json

Adds rule to disable adding spaces between curly braces for imports within VSCode.

Remove vscode rule to add space between curly braces

---

src/components/encoding-pane/encoding-shelf.tsx
src/components/encoding-pane/property-editor-schema.ts

Fix #804 
Disable customizer popup caret option for Detail channel. 
Created constant for channels that support encoding customization.
Brief demo showing customizer doesn't display caret for channels that have no customization supported yet.

Filter customizers only for channels that support customization

---

src/components/encoding-pane/property-editor-schema.ts

Fix #803 
According to VL documentation, `stack is only applicable for x and y channels with continuous domains`. 
This PR adds a filter to only show `stack` property when domain is continuous.

Add filter to only show stack property when domain is continuous

---

package.json

Travis CI takes much longer than it should to run Jest tests, and the goal of this PR is to speed up CI, as current Travis builds for Voyager take over 15 minutes. 
According to Jest: "This defaults to the number of the cores available on your machine. It may be useful to adjust this in resource limited environments like CIs"
With the `maxWorkers` flag, CI build time is around 7-8 minutes.

Add maxWorkers flag to speed up Jest tests for CI

---

README.md

timestamp in readme did not link to correct location in video. Fixed URL to use seconds

timestamp corrected in README
